name: jro_units_converter
description: Simple and light units conversion package for all your needs.
version: 0.3.0+1
homepage: https://github.com/copypasteearth/units_converter

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
